site_name: Asas-py Documentation
repo_url: https://github.com/HeshamMoawad/asas-py
repo_name: HeshamMoawad/asas-py
site_url: https://heshammoawad.github.io/asas-py/
plugins:
  - search
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ar
          name: العربية
          build: true
      fallback_to_default: true
# nav:
#   - Home: index.md
#   - Guide:
#       - English: en/index.md
#       - العربية: ar/index.md
theme:
  name: material
  favicon: assets/logo-without-bg.png
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

# Extra CSS to make colors consistent with your logo
extra_css:
  - stylesheets/extra.css
