[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asas-py"
version = "0.0.1"
authors = [
  { name="Hesham Moawad", email="heshammoawad120120@gmail.com" },
]
description = "The elegant, type-safe Python API client builder."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
Homepage = "https://github.com/HeshamMoawad/asas-py"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88
